# Building instructions:
#
# - copy the zip file with all the students' code to students.zip
#   (this zip file will get extracted inside the container at build time)
# - build the image with:
#   docker build -t grading -f Dockerfile.grading .
#
# - run the image with:
#   docker run --rm -it -v `pwd`/results:/app/results grading

FROM python:3.14.2-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# setup venv
WORKDIR /app
COPY pyproject.toml uv.lock .
RUN uv venv --python 3.14.2 && \
    uv sync && \
    apt-get update && \
    apt-get install -y zip rename

# unzip
COPY students.zip .
COPY grading ./grading
COPY unzip.sh .
RUN ./unzip.sh

# setup code
COPY common ./common
COPY maps ./maps
COPY server ./server
COPY config.json .

VOLUME /app/results

ENTRYPOINT ["/bin/bash", "-c", "source ./.venv/bin/activate && python -m grading"]
